#!/bin/bash
# Copyright (C) 2018-2019 Andreas Huber Dönni
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If not, see
# <http://www.gnu.org/licenses/>.

set -o errexit
set -o nounset
set -o pipefail

pushd $(cd `dirname "${BASH_SOURCE[0]}"` && pwd)

echo "Creating release branch..."
VERSION=`npm version patch --no-git-tag-version`
git checkout .
git flow release start ${VERSION}
npm version patch --no-git-tag-version
git commit -a -m "Start release v1.0.42"
git push origin --all

popd
